### ISSUE TITLE
A right to left page curl lead touch event

### ISSUE THREAD

**Issue by uintaam** [harism/android-pagecurl#6]
I think it would look a bit more natural if a right to left page curl were to lead the touch event in SHOW_ONE_PAGE mode. 

Start by changing the onSizeChanged funtion in CurlActivity to this

public void onSizeChanged(int w, int h) {
    mCurlView.setViewMode(CurlView.SHOW_ONE_PAGE);
    mCurlView.setMargins(.1f, .5f, .1f, .5f);
}

If view the application in landscape mode and do a right to left page curl the the curl will never reach the left side of the screen;  But if you do a left to right curl the animation will look very nice when moving your finger left and right.

**Comment by harism** [comment]
I think you're explaining one of the most annoying things I've been pondering over while dealing with this subject so far. How to handle page flipping from side to side. And only thing I came up with was following.

Once we receive pointer event, let's say on right side, idea was to let user drag right edge of paper. But once it's dragged over the middle of book to left side 'problems' arise. Namely, how to continue from there, while all what is needed is to have page laid on opposite side smoothly. And currently curl movement stops at book middle actually, never passing it, and from then on curl/cylinder radius is decreased only. And once radius is zero we have a 100% page flip. Now this would look extremely stupid looking from arbitrary angle but since we have fixed point of view it's not 'that bad'.

In one page mode, if you start dragging left page, I tried a bit different approach. Instead of letting user drag edge of paper, it's the curl which follows pointer. Meaning that at left edge curl radius is still zero but will be higher until it reaches right edge.

Now the real problem is to decide what you actually want to do. If you have an open book visible, you pretty much have to come up with some idea how to make transition e.g. from right to left. While if the use case is limited to one visible page only, there are alternatives to make transition from right to left more smoother (esp. compared to what I've being doing so far). Ultimately you just have to figure out a way how to let page rotate over left side of screen and don't have to care how it looks as it's invisible for user anyway.

This is mainly due to the way I started dealing with the subject. There is only a cylinder we are moving on the page for receiving a transition. If there was rotation added it might ease the situation a bit - but made it much harder to interact with the user simultaneously. And, well, I decided to give an open book a try  :)

But as said. As long as you limit the problem to one visible page only there really are some much better looking alternatives for handling the transition. And quite obviously for an open book too - I just haven't figured out how exactly. And compared to one visible page there aren't many videos on e.g YouTube showing how it could be done with an open book  :(

**Comment by harism** [comment]
Still on this topic. After doing some searching on YouTube, once again, for inspiration, I found this video;
http://www.youtube.com/watch?v=aqXolf4aOPU

Only problem is that transition is so quick in this video, and they don't show dragging almost at all, it's hard to see if there was something to learn here. Now I'm mostly wondering is this EPad tablet they are using powerful enough to handle proper page transition at all. But then again, in an eReader, page transition is only a minor speed bump compared to other much more complex usability issues.

**Comment by uintaam** [comment]
Here's a screen shot of what I'm describing above.  http://www.image-share.com/ipng-639-96.html
My finger position is indicated by the black dot in the bottom left.  You can see how the curl is farther behind the actual touch position.  

What about adding additional distance to the curl position, as your finger approaches the left edge, when moving a page from right to left.

**Comment by harism** [comment]
Ah, I see, seeing this image clearly shows an unwanted error in curl position calculation. Will give it a look asap.

**Comment by harism** [comment]
I wasn't able to reproduce similar behavior. Could you provide me with margin values you're using? The ones in original message mCurlView.setMargins(.1f, .5f, .1f, .5f), produce a page of height zero (50% margin for top and bottom).

**Comment by uintaam** [comment]
It's possible it's a device specific issue.  I don't have my device at the moment as my other developer took it, I'll be able test it again tomorrow.

**Comment by uintaam** [comment]
The device is a Motorola Zoom running Android 3.
Also, it's happening on our galaxy S running 2.2.
margins .0f,.0f,.0f,.0f

**Comment by harism** [comment]
Ok, will give it a go later today. Zero margins is something I haven't played with for a while.

**Comment by harism** [comment]
I still had problems reproducing this error and get to figure out what's happening. Anyway, I ordered Android phone, finally, few days ago. Hope it provides me with more possibilities to tackle with this issue.

**Comment by uintaam** [comment]
I should also mention I have the left page render set to false.  This could be the issue.

**Comment by uintaam** [comment]
Fixed in pull request for issue #9.
